objects/C_Suite_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>C-Suite Contacts</relationshipLabel>
        <relationshipName>C_Suite_Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>C-Suite Contacts</relationshipLabel>
        <relationshipName>C_Suite_Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>C-Suite Contact</label>
    <nameField>
        <label>C-Suite Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>C-Suite Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CSuiteLogic.cls
public class CSuiteLogic {
    
    public static void createCSuiteContact( List<Contact> passedCons ) {
        List<Contact> cons = queryContractFields(passedCons);
        List<C_Suite_Contact__c> csuites;
        
        if ( !cons.isEmpty() ) {
            
            csuites = new List<C_Suite_Contact__c>();
            
            for( Contact con : cons ){
                
                if ( checkcSuite(con) && con.AccountId != null ) {
                    C_Suite_Contact__c csc = new C_Suite_Contact__c();
                    csc.Account__c = con.AccountId;
                    csc.Contact__c = con.id;
                    csc.Title__c = con.Title;
                    csc.Name = con.Account.name + ' - ' + con.Title;
                    csuites.add(csc);
                }   
            } 
            try {
                
                insert csuites;
                
            } catch(DMLException e) {
                
                System.debug('Error in createCSuiteContact = ' + e);
                System.debug('Error line in createCSuiteContact = ' + e.getLineNumber());
                System.debug('Error cause in createCSuiteContact = ' + e.getCause());
            
            }
        } 
    }
    public static List<Contact> queryContractFields(List<Contact> cons){
        
        Set<Id>conIds = new Set<Id>();
        for(Contact con : cons){
            conIds.add(con.id);
        }
        if(!conIds.isEmpty()){
            List<Contact> retCons = [SELECT id,
                                        AccountId,
                                        Title,
                                        Account.name
                                     FROM Contact 
                                     WHERE id IN :conIds];
            return retCons;
            
        }
        return null;
    }
    
    public static Boolean checkcSuite( Contact con) {

        if ( !String.isEmpty(con.Title) ) {
            if(con.Title.contains('CFO') ||
              con.Title.contains('CIO') ||
              con.Title.contains('CEO') ||
              con.Title.contains('CMO') ||
              con.Title.contains('COO') ||
              con.Title.contains('CDO') ||
              con.Title.contains('Chief')) {
                  
               return true; 
                  
            } else {
                
                return false;
            }
            
        } else {
            
            return false;
        }
    }
}